In [1]:
import pandas as pd
import datetime as dt
import matplotlib as plt
from sqlalchemy import create_engine

In [2]:
path="Resources/googletrends.csv"

data = pd.read_csv(path) 

data.columns=['date','CERB','Mask','Bike','Zoom', 'Patio']
data=data.drop(data.index[[0,1]])
data=data.reset_index()
data.head()

   index        date CERB Mask Bike Zoom Patio
0      2  01-01-2020   <1    5    7    1     1
1      3  02-01-2020   <1    4    7    2     1
2      4  03-01-2020   <1    5    7    1     1
3      5  04-01-2020   <1    4    8    2     1
4      6  05-01-2020    0    5    8    2     1

In [3]:
trend_df=data.drop('index', axis=1)
trend_df.head()

         date CERB Mask Bike Zoom Patio
0  01-01-2020   <1    5    7    1     1
1  02-01-2020   <1    4    7    2     1
2  03-01-2020   <1    5    7    1     1
3  04-01-2020   <1    4    8    2     1
4  05-01-2020    0    5    8    2     1

In [4]:


trend_df['CERB'] = trend_df['CERB'].replace(
    {'<1': '0'})

In [5]:
trend_df['CERB']=trend_df['CERB'].astype('str', copy=True).astype('float', copy=True)
trend_df['Mask']=trend_df['Mask'].astype('str', copy=True).astype('float', copy=True)
trend_df['Bike']=trend_df['Bike'].astype('str', copy=True).astype('float', copy=True)
trend_df['Zoom']=trend_df['Zoom'].astype('str', copy=True).astype('float', copy=True)
trend_df['Patio']=trend_df['Patio'].astype('str', copy=True).astype('float', copy=True)

trend_df.dtypes

date      object
CERB     float64
Mask     float64
Bike     float64
Zoom     float64
Patio    float64
dtype: object

In [6]:
trend_df.head()

         date  CERB  Mask  Bike  Zoom  Patio
0  01-01-2020   0.0   5.0   7.0   1.0    1.0
1  02-01-2020   0.0   4.0   7.0   2.0    1.0
2  03-01-2020   0.0   5.0   7.0   1.0    1.0
3  04-01-2020   0.0   4.0   8.0   2.0    1.0
4  05-01-2020   0.0   5.0   8.0   2.0    1.0

In [7]:
n_path="Resources/covid19.csv"

cdata = pd.read_csv(n_path) 
cdata.head()

,pruid,prname,prnameFR,date,numconf,numprob,numdeaths,numtotal,numtested,numrecover,...,percentdeath,numtestedtoday,numrecoveredtoday,percentactive,numactive,rateactive,numtotal_last14,ratetotal_last14,numdeaths_last14,ratedeaths_last14
0,35,Ontario,Ontario,31-01-2020,3,0,0.0,3,NaN,NaN,...,0.0,NaN,NaN,100.0,3.0,0.02,NaN,NaN,NaN,NaN
1,59,British Columbia,Colombie-Britannique,31-01-2020,1,0,0.0,1,NaN,NaN,...,0.0,NaN,NaN,100.0,1.0,0.02,NaN,NaN,NaN,NaN
2,1,Canada,Canada,31-01-2020,4,0,0.0,4,NaN,NaN,...,0.0,NaN,NaN,100.0,4.0,0.01,NaN,NaN,NaN,NaN
3,35,Ontario,Ontario,08-02-2020,3,0,0.0,3,NaN,NaN,...,0.0,NaN,NaN,100.0,3.0,0.02,NaN,NaN,NaN,NaN
4,59,British Columbia,Colombie-Britannique,08-02-2020,4,0,0.0,4,NaN,NaN,...,0.0,NaN,NaN,100.0,4.0,0.08,NaN,NaN,NaN,NaN

In [8]:
cdata['prname']=cdata['prname'].astype('str', copy=True)

In [9]:
candata=cdata[[ 'date','prname','numconf','numdeaths','numtoday','numdeathstoday','numtested','numtestedtoday','numrecover', 
     'numrecoveredtoday','numactive'
     ]]

In [10]:
candata["numtoday"] = candata["numtoday"].fillna(0).copy()
candata["numdeaths"] = candata["numdeaths"].fillna(0).copy()
candata["numdeathstoday"] = candata["numdeathstoday"].fillna(0).copy()
candata["numtested"] = candata["numtested"].fillna(0).copy()
candata["numtestedtoday"] = candata["numtestedtoday"].fillna(0).copy()
candata["numrecover"] = candata["numrecover"].fillna(0).copy()
candata["numrecoveredtoday"] = candata["numrecoveredtoday"].fillna(0).copy()
candata["numactive"] = candata["numactive"].fillna(0).copy()

/Users/angelaromansivirichi/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/Users/angelaromansivirichi/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/Users/angelaromansivirichi/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/Users/angelaromansivirichi/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/Users/angelaromansivirichi/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/Users/angelaromansivirichi/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/Users/angelaromansivirichi/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
/Users/angelaromansivirichi/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [11]:
candata.head(10)

,date,prname,numconf,numdeaths,numtoday,numdeathstoday,numtested,numtestedtoday,numrecover,numrecoveredtoday,numactive
0,31-01-2020,Ontario,3,0.0,3,0.0,0.0,0.0,0.0,0.0,3.0
1,31-01-2020,British Columbia,1,0.0,1,0.0,0.0,0.0,0.0,0.0,1.0
2,31-01-2020,Canada,4,0.0,4,0.0,0.0,0.0,0.0,0.0,4.0
3,08-02-2020,Ontario,3,0.0,0,0.0,0.0,0.0,0.0,0.0,3.0
4,08-02-2020,British Columbia,4,0.0,3,0.0,0.0,0.0,0.0,0.0,4.0
5,08-02-2020,Canada,7,0.0,3,0.0,0.0,0.0,0.0,0.0,7.0
6,16-02-2020,Ontario,3,0.0,0,0.0,0.0,0.0,0.0,0.0,3.0
7,16-02-2020,British Columbia,5,0.0,1,0.0,0.0,0.0,0.0,0.0,5.0
8,16-02-2020,Canada,8,0.0,1,0.0,0.0,0.0,0.0,0.0,8.0
9,21-02-2020,Ontario,3,0.0,0,0.0,0.0,0.0,0.0,0.0,3.0

In [12]:
provinces_url = "https://www.latlong.net/category/provinces-40-60.html"
territories_url = "https://www.latlong.net/category/territories-40-61.html"
popullation_url ="https://worldpopulationreview.com/canadian-provinces"

provinces_tables = pd.read_html(provinces_url)
territories_tables = pd.read_html(territories_url)
population_tables = pd.read_html(popullation_url)

prov_lat_long_df = provinces_tables[0]
terr_lat_long_df = territories_tables[0]
population_df = population_tables[0]

In [13]:
#population
population_2019_df=population_df.drop(['2016 Population', '2011 Population'], axis=1)
population_2019_df = population_2019_df.sort_values(by='Name', ascending=True)
population_2019_df.reset_index(drop = True, inplace=True)
population_2019_df

                    Name  2019 Population
0                Alberta          4345737
1       British Columbia          5020302
2               Manitoba          1360396
3          New Brunswick           772094
4           Newfoundland           523790
5    Northwest Territory            44598
6            Nova Scotia           965382
7                Nunavut            38787
8                Ontario         14446515
9   Prince Edward Island           154748
10                Quebec          8433301
11          Saskatchewan          1168423
12                 Yukon            40369

In [14]:
#coordinates
coordinates_df = pd.concat([prov_lat_long_df, terr_lat_long_df])
clean_coordinates_df = coordinates_df.reset_index(drop = True).drop(8)
canada_coordinates_df = clean_coordinates_df.reset_index(drop = True)
canada_coordinates_df.loc['12'] = ['Northwest Territories', '64.8255', '-124.8457']
canada_coordinates_df = canada_coordinates_df.sort_values(by='Place Name', ascending=True)
canada_coordinates_df.reset_index(drop = True, inplace=True)
canada_coordinates_df

                                    Place Name Latitude  Longitude
0                     Alberta Province, Canada       55       -115
1                     British Columbia, Canada  53.7267   -127.648
2                             Manitoba, Canada  56.4152   -98.7391
3                        New Brunswick, Canada  46.4984   -66.1597
4   Newfoundland and Labrador Province, Canada       53        -60
5                        Northwest Territories  64.8255  -124.8457
6                          Nova Scotia, Canada       45        -63
7                              Nunavut, Canada  70.4533    -86.799
8                     Ontario Province, Canada       50        -85
9                 Prince Edward Island, Canada    46.25        -63
10                     Quebec Province, Canada       53        -70
11               Saskatchewan Province, Canada       55       -106
12                     Yukon Territory, Canada       64       -135

In [15]:
#population and coordines combined
territories = pd.concat([population_2019_df, canada_coordinates_df], axis=1, join='inner')
territories_df = territories.drop(['Place Name'], axis=1)
territories_df.rename(columns={'2019 Population': 'population', 'Latitude': 'latitude', 'Longitude': 'longitude'}, inplace=True)
territories_df.rename(columns={'Name': 'prname'}, inplace=True)
territories_df['prname'] = territories_df['prname'].replace(['Newfoundland'],'Newfoundland and Labrador')
territories_df['prname'] = territories_df['prname'].replace(['Northwest Territory'],'Northwest Territories')

In [16]:
canada_covid_df = candata.merge(territories_df, on='prname', how='outer')
canada_covid_df.sample(40)

,date,prname,numconf,numdeaths,numtoday,numdeathstoday,numtested,numtestedtoday,numrecover,numrecoveredtoday,numactive,population,latitude,longitude
2374,24-03-2020,Nunavut,0,0.0,0,0.0,81.0,68.0,0.0,0.0,0.0,38787.0,70.4533,-86.799
2464,22-06-2020,Nunavut,0,0.0,0,0.0,992.0,3.0,0.0,0.0,0.0,38787.0,70.4533,-86.799
1677,03-06-2020,Newfoundland and Labrador,261,3.0,0,0.0,12601.0,168.0,256.0,0.0,2.0,523790.0,53,-60
427,05-03-2020,Canada,45,0.0,12,0.0,0.0,0.0,0.0,0.0,45.0,NaN,NaN,NaN
1355,04-08-2020,Manitoba,428,8.0,1,0.0,91697.0,5122.0,341.0,4.0,94.0,1360396.0,56.4152,-98.7391
732,20-06-2020,Quebec,54674,5408.0,124,33.0,551352.0,6187.0,23201.0,229.0,26065.0,8433301.0,53,-70
1464,13-05-2020,New Brunswick,120,0.0,0,0.0,17765.0,426.0,118.0,0.0,2.0,772094.0,46.4984,-66.1597
943,07-07-2020,Alberta,8436,157.0,47,2.0,431102.0,4789.0,7659.0,32.0,620.0,4345737.0,55,-115
641,21-03-2020,Quebec,202,4.0,82,3.0,8539.0,0.0,0.0,0.0,217.0,8433301.0,53,-70
434,13-03-2020,Canada,176,2.0,38,0.0,15185.0,0.0,0.0,0.0,177.0,NaN,NaN,NaN
423,27-02-2020,Canada,13,0.0,1,0.0,0.0,0.0,0.0,0.0,13.0,NaN,NaN,NaN
215,27-02-2020,British Columbia,7,0.0,0,0.0,0.0,0.0,0.0,0.0,7.0,5020302.0,53.7267,-127.648
2879,23-07-2020,Repatriated travellers,13,0.0,0,0.0,76.0,0.0,13.0,0.0,0.0,NaN,NaN,NaN
1902,06-07-2020,Nova Scotia,1065,63.0,1,0.0,56236.0,204.0,998.0,0.0,4.0,965382.0,45,-63
1098,31-05-2020,Saskatchewan,646,11.0,1,1.0,43284.0,610.0,582.0,2.0,53.0,1168423.0,55,-106
2098,10-07-2020,Prince Edward Island,33,0.0,0,0.0,13872.0,207.0,27.0,0.0,6.0,154748.0,46.25,-63
762,20-07-2020,Quebec,57616,5657.0,150,2.0,747943.0,9506.0,50190.0,140.0,1769.0,8433301.0,53,-70
1287,28-05-2020,Manitoba,283,7.0,2,0.0,40709.0,919.0,273.0,2.0,14.0,1360396.0,56.4152,-98.7391
1683,09-06-2020,Newfoundland and Labrador,261,3.0,0,0.0,13705.0,282.0,256.0,0.0,2.0,523790.0,53,-60
2559,17-03-2020,Yukon,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,40369.0,64,-135
1668,25-05-2020,Newfoundland and Labrador,260,3.0,0,0.0,11333.0,48.0,254.0,0.0,3.0,523790.0,53,-60
2553,11-03-2020,Yukon,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,40369.0,64,-135
1519,07-07-2020,New Brunswick,165,2.0,0,0.0,39652.0,217.0,162.0,0.0,1.0,772094.0,46.4984,-66.1597
1511,29-06-2020,New Brunswick,165,2.0,0,0.0,38086.0,167.0,158.0,0.0,5.0,772094.0,46.4984,-66.1597
1401,11-03-2020,New Brunswick,0,0.0,0,0.0,22.0,22.0,0.0,0.0,0.0,772094.0,46.4984,-66.1597
1650,07-05-2020,Newfoundland and Labrador,261,3.0,2,0.0,9451.0,156.0,244.0,0.0,14.0,523790.0,53,-60
9,01-03-2020,Ontario,15,0.0,7,0.0,0.0,0.0,0.0,0.0,15.0,14446515.0,50,-85
2750,16-03-2020,Repatriated travellers,4,0.0,0,0.0,29.0,0.0,0.0,0.0,4.0,NaN,NaN,NaN
595,21-08-2020,Canada,124372,9064.0,499,10.0,5034059.0,59844.0,110648.0,360.0,4660.0,NaN,NaN,NaN
2188,30-03-2020,Northwest Territories,1,0.0,0,0.0,740.0,0.0,0.0,0.0,1.0,44598.0,64.8255,-124.8457
2393,12-04-2020,Nunavut,0,0.0,0,0.0,264.0,3.0,0.0,0.0,0.0,38787.0,70.4533,-86.799
1557,14-08-2020,New Brunswick,180,2.0,0,0.0,49295.0,263.0,169.0,0.0,9.0,772094.0,46.4984,-66.1597
1473,22-05-2020,New Brunswick,121,0.0,0,0.0,20309.0,205.0,120.0,0.0,1.0,772094.0,46.4984,-66.1597
1512,30-06-2020,New Brunswick,165,2.0,0,0.0,38261.0,175.0,159.0,1.0,4.0,772094.0,46.4984,-66.1597
430,08-03-2020,Canada,62,1.0,5,1.0,0.0,0.0,0.0,0.0,61.0,NaN,NaN,NaN
998,31-08-2020,Alberta,13902,239.0,426,2.0,767296.0,23243.0,12293.0,239.0,1370.0,4345737.0,55,-115
568,25-07-2020,Canada,113543,8885.0,350,4.0,3761927.0,44444.0,99115.0,242.0,5556.0,NaN,NaN,NaN
1153,25-07-2020,Saskatchewan,1136,16.0,37,0.0,77846.0,1531.0,862.0,14.0,258.0,1168423.0,55,-106
179,21-08-2020,Ontario,41179,2796.0,131,3.0,2622281.0,27155.0,37397.0,106.0,986.0,14446515.0,50,-85
121,24-06-2020,Ontario,34016,2631.0,163,12.0,1195605.0,22448.0,29336.0,229.0,2049.0,14446515.0,50,-85

In [17]:
canada_df=canada_covid_df.loc[canada_covid_df["prname"]=="Canada"]

In [18]:
canada_df=canada_df[["date", "numconf","numtestedtoday","numtoday","numdeathstoday", "numactive"]]

In [19]:
covid_trends_df=canada_df.merge(trend_df, on='date', how='inner')

In [20]:
covid_trends_df

,date,numconf,numtestedtoday,numtoday,numdeathstoday,numactive,CERB,Mask,Bike,Zoom,Patio
0,31-01-2020,4,0.0,4,0.0,4.0,0.0,17.0,7.0,2.0,1.0
1,08-02-2020,7,0.0,3,0.0,7.0,0.0,10.0,7.0,3.0,1.0
2,16-02-2020,8,0.0,1,0.0,8.0,0.0,8.0,9.0,2.0,2.0
3,21-02-2020,9,0.0,1,0.0,9.0,0.0,6.0,6.0,2.0,1.0
4,24-02-2020,10,0.0,1,0.0,10.0,0.0,7.0,8.0,3.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...
201,12-09-2020,136141,22922.0,515,7.0,6896.0,7.0,19.0,18.0,8.0,6.0
202,13-09-2020,136659,85216.0,518,1.0,7057.0,7.0,20.0,18.0,10.0,5.0
203,14-09-2020,138010,80997.0,1351,8.0,7607.0,10.0,19.0,14.0,19.0,4.0
204,15-09-2020,138803,56695.0,793,9.0,7775.0,11.0,19.0,15.0,20.0,4.0
205,16-09-2020,139747,62497.0,944,5.0,8105.0,10.0,19.0,12.0,21.0,5.0

In [21]:
covid_trends_df.columns.tolist()

['date',
 'numconf',
 'numtestedtoday',
 'numtoday',
 'numdeathstoday',
 'numactive',
 'CERB',
 'Mask',
 'Bike',
 'Zoom',
 'Patio']

In [22]:
canada_covid_df.columns.tolist()

['date',
 'prname',
 'numconf',
 'numdeaths',
 'numtoday',
 'numdeathstoday',
 'numtested',
 'numtestedtoday',
 'numrecover',
 'numrecoveredtoday',
 'numactive',
 'population',
 'latitude',
 'longitude']

In [26]:
# change the xxxx to your postgreSQL password when you run the code

#connection_string = "postgres://postgres:123@localhost:5432/covid_vision"
#engine = create_engine(f'postgresql://{connection_string}')

engine = create_engine(f'postgresql+psycopg2://postgres:{123}@localhost:5432/covid_vision')

In [28]:
engine.table_names()

['canada_covid', 'covid_trends']

In [29]:
covid_trends_df.to_sql(name = "covid_trends", con=engine, if_exists = 'append', index = True)

In [30]:
canada_covid_df.to_sql(name = "canada_covid", con=engine, if_exists = 'append', index = True)