In [1]:
import pandas as pd
import datetime as dt
import matplotlib as plt
from sqlalchemy import create_engine

In [2]:
path="Resources/googletrends.csv"

data = pd.read_csv(path) 

data.columns=['date','CERB','Mask','Bike','Zoom', 'Patio']
data=data.drop(data.index[[0,1]])
data=data.reset_index()
data.head()

   index        date CERB Mask Bike Zoom Patio
0      2  01-01-2020   <1    5    7    1     1
1      3  02-01-2020   <1    4    7    2     1
2      4  03-01-2020   <1    5    7    1     1
3      5  04-01-2020   <1    4    8    2     1
4      6  05-01-2020    0    5    8    2     1

In [3]:
trend_df=data.drop('index', axis=1)
trend_df.head()

         date CERB Mask Bike Zoom Patio
0  01-01-2020   <1    5    7    1     1
1  02-01-2020   <1    4    7    2     1
2  03-01-2020   <1    5    7    1     1
3  04-01-2020   <1    4    8    2     1
4  05-01-2020    0    5    8    2     1

In [4]:


trend_df['CERB'] = trend_df['CERB'].replace(
    {'<1': '0'})

In [5]:
trend_df['CERB']=trend_df['CERB'].astype('str', copy=True).astype('float', copy=True)
trend_df['Mask']=trend_df['Mask'].astype('str', copy=True).astype('float', copy=True)
trend_df['Bike']=trend_df['Bike'].astype('str', copy=True).astype('float', copy=True)
trend_df['Zoom']=trend_df['Zoom'].astype('str', copy=True).astype('float', copy=True)
trend_df['Patio']=trend_df['Patio'].astype('str', copy=True).astype('float', copy=True)

trend_df.dtypes

date      object
CERB     float64
Mask     float64
Bike     float64
Zoom     float64
Patio    float64
dtype: object

In [6]:
trend_df.head()

         date  CERB  Mask  Bike  Zoom  Patio
0  01-01-2020   0.0   5.0   7.0   1.0    1.0
1  02-01-2020   0.0   4.0   7.0   2.0    1.0
2  03-01-2020   0.0   5.0   7.0   1.0    1.0
3  04-01-2020   0.0   4.0   8.0   2.0    1.0
4  05-01-2020   0.0   5.0   8.0   2.0    1.0

In [7]:
n_path="Resources/covid19.csv"

cdata = pd.read_csv(n_path) 
cdata.head()

,pruid,prname,prnameFR,date,numconf,numprob,numdeaths,numtotal,numtested,numrecover,...,percentdeath,numtestedtoday,numrecoveredtoday,percentactive,numactive,rateactive,numtotal_last14,ratetotal_last14,numdeaths_last14,ratedeaths_last14
0,35,Ontario,Ontario,31-01-2020,3,0,0.0,3,NaN,NaN,...,0.0,NaN,NaN,100.0,3.0,0.02,NaN,NaN,NaN,NaN
1,59,British Columbia,Colombie-Britannique,31-01-2020,1,0,0.0,1,NaN,NaN,...,0.0,NaN,NaN,100.0,1.0,0.02,NaN,NaN,NaN,NaN
2,1,Canada,Canada,31-01-2020,4,0,0.0,4,NaN,NaN,...,0.0,NaN,NaN,100.0,4.0,0.01,NaN,NaN,NaN,NaN
3,35,Ontario,Ontario,08-02-2020,3,0,0.0,3,NaN,NaN,...,0.0,NaN,NaN,100.0,3.0,0.02,NaN,NaN,NaN,NaN
4,59,British Columbia,Colombie-Britannique,08-02-2020,4,0,0.0,4,NaN,NaN,...,0.0,NaN,NaN,100.0,4.0,0.08,NaN,NaN,NaN,NaN

In [8]:
cdata['prname']=cdata['prname'].astype('str', copy=True)

In [9]:
candata=cdata[[ 'date','prname','numconf','numdeaths','numtoday','numdeathstoday','numtested','numtestedtoday','numrecover', 
     'numrecoveredtoday','numactive'
     ]]

In [10]:
candata["numtoday"] = candata["numtoday"].fillna(0).copy()
candata["numdeaths"] = candata["numdeaths"].fillna(0).copy()
candata["numdeathstoday"] = candata["numdeathstoday"].fillna(0).copy()
candata["numtested"] = candata["numtested"].fillna(0).copy()
candata["numtestedtoday"] = candata["numtestedtoday"].fillna(0).copy()
candata["numrecover"] = candata["numrecover"].fillna(0).copy()
candata["numrecoveredtoday"] = candata["numrecoveredtoday"].fillna(0).copy()
candata["numactive"] = candata["numactive"].fillna(0).copy()

/Users/tajudeenadeyemi/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/Users/tajudeenadeyemi/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/Users/tajudeenadeyemi/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/Users/tajudeenadeyemi/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/Users/tajudeenadeyemi/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/Users/tajudeenadeyemi/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/Users/tajudeenadeyemi/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
/Users/tajudeenadeyemi/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [11]:
candata.head(10)

,date,prname,numconf,numdeaths,numtoday,numdeathstoday,numtested,numtestedtoday,numrecover,numrecoveredtoday,numactive
0,31-01-2020,Ontario,3,0.0,3,0.0,0.0,0.0,0.0,0.0,3.0
1,31-01-2020,British Columbia,1,0.0,1,0.0,0.0,0.0,0.0,0.0,1.0
2,31-01-2020,Canada,4,0.0,4,0.0,0.0,0.0,0.0,0.0,4.0
3,08-02-2020,Ontario,3,0.0,0,0.0,0.0,0.0,0.0,0.0,3.0
4,08-02-2020,British Columbia,4,0.0,3,0.0,0.0,0.0,0.0,0.0,4.0
5,08-02-2020,Canada,7,0.0,3,0.0,0.0,0.0,0.0,0.0,7.0
6,16-02-2020,Ontario,3,0.0,0,0.0,0.0,0.0,0.0,0.0,3.0
7,16-02-2020,British Columbia,5,0.0,1,0.0,0.0,0.0,0.0,0.0,5.0
8,16-02-2020,Canada,8,0.0,1,0.0,0.0,0.0,0.0,0.0,8.0
9,21-02-2020,Ontario,3,0.0,0,0.0,0.0,0.0,0.0,0.0,3.0

In [12]:
provinces_url = "https://www.latlong.net/category/provinces-40-60.html"
territories_url = "https://www.latlong.net/category/territories-40-61.html"
popullation_url ="https://worldpopulationreview.com/canadian-provinces"

provinces_tables = pd.read_html(provinces_url)
territories_tables = pd.read_html(territories_url)
population_tables = pd.read_html(popullation_url)

prov_lat_long_df = provinces_tables[0]
terr_lat_long_df = territories_tables[0]
population_df = population_tables[0]

In [13]:
#population
population_2019_df=population_df.drop(['2016 Population', '2011 Population'], axis=1)
population_2019_df = population_2019_df.sort_values(by='Name', ascending=True)
population_2019_df.reset_index(drop = True, inplace=True)
population_2019_df

                    Name  2019 Population
0                Alberta          4345737
1       British Columbia          5020302
2               Manitoba          1360396
3          New Brunswick           772094
4           Newfoundland           523790
5    Northwest Territory            44598
6            Nova Scotia           965382
7                Nunavut            38787
8                Ontario         14446515
9   Prince Edward Island           154748
10                Quebec          8433301
11          Saskatchewan          1168423
12                 Yukon            40369

In [14]:
#coordinates
coordinates_df = pd.concat([prov_lat_long_df, terr_lat_long_df])
clean_coordinates_df = coordinates_df.reset_index(drop = True).drop(8)
canada_coordinates_df = clean_coordinates_df.reset_index(drop = True)
canada_coordinates_df.loc['12'] = ['Northwest Territories', '64.8255', '-124.8457']
canada_coordinates_df = canada_coordinates_df.sort_values(by='Place Name', ascending=True)
canada_coordinates_df.reset_index(drop = True, inplace=True)
canada_coordinates_df

                                    Place Name Latitude  Longitude
0                     Alberta Province, Canada       55       -115
1                     British Columbia, Canada  53.7267   -127.648
2                             Manitoba, Canada  56.4152   -98.7391
3                        New Brunswick, Canada  46.4984   -66.1597
4   Newfoundland and Labrador Province, Canada       53        -60
5                        Northwest Territories  64.8255  -124.8457
6                          Nova Scotia, Canada       45        -63
7                              Nunavut, Canada  70.4533    -86.799
8                     Ontario Province, Canada       50        -85
9                 Prince Edward Island, Canada    46.25        -63
10                     Quebec Province, Canada       53        -70
11               Saskatchewan Province, Canada       55       -106
12                     Yukon Territory, Canada       64       -135

In [15]:
#population and coordines combined
territories = pd.concat([population_2019_df, canada_coordinates_df], axis=1, join='inner')
territories_df = territories.drop(['Place Name'], axis=1)
territories_df.rename(columns={'2019 Population': 'population', 'Latitude': 'latitude', 'Longitude': 'longitude'}, inplace=True)
territories_df.rename(columns={'Name': 'prname'}, inplace=True)
territories_df['prname'] = territories_df['prname'].replace(['Newfoundland'],'Newfoundland and Labrador')
territories_df['prname'] = territories_df['prname'].replace(['Northwest Territory'],'Northwest Territories')

In [16]:
canada_covid_df = candata.merge(territories_df, on='prname', how='outer')
canada_covid_df.sample(40)

,date,prname,numconf,numdeaths,numtoday,numdeathstoday,numtested,numtestedtoday,numrecover,numrecoveredtoday,numactive,population,latitude,longitude
2207,18-04-2020,Northwest Territories,5,0.0,0,0.0,1459.0,12.0,3.0,3.0,2.0,44598.0,64.8255,-124.8457
1026,20-03-2020,Saskatchewan,8,0.0,6,0.0,1910.0,0.0,0.0,0.0,26.0,1168423.0,55,-106
1005,07-09-2020,Alberta,14474,242.0,0,0.0,816374.0,23409.0,12799.0,0.0,1433.0,4345737.0,55,-115
2459,17-06-2020,Nunavut,0,0.0,0,0.0,949.0,14.0,0.0,0.0,0.0,38787.0,70.4533,-86.799
517,04-06-2020,Canada,93715,7637.0,641,139.0,1791106.0,35180.0,51739.0,691.0,34350.0,NaN,NaN,NaN
495,13-05-2020,Canada,72267,5304.0,1121,135.0,1172872.0,27304.0,35164.0,1122.0,31810.0,NaN,NaN,NaN
1395,13-09-2020,Manitoba,1428,16.0,18,0.0,148326.0,0.0,1173.0,17.0,239.0,1360396.0,56.4152,-98.7391
2201,12-04-2020,Northwest Territories,5,0.0,0,0.0,1386.0,16.0,0.0,0.0,5.0,44598.0,64.8255,-124.8457
2613,10-05-2020,Yukon,11,0.0,0,0.0,1075.0,0.0,11.0,0.0,0.0,40369.0,64,-135
116,19-06-2020,Ontario,33095,2564.0,178,11.0,1087179.0,26334.0,28250.0,246.0,2281.0,14446515.0,50,-85
2063,05-06-2020,Prince Edward Island,27,0.0,0,0.0,7111.0,186.0,27.0,0.0,0.0,154748.0,46.25,-63
430,08-03-2020,Canada,62,1.0,5,1.0,0.0,0.0,0.0,0.0,61.0,NaN,NaN,NaN
865,20-04-2020,Alberta,2908,59.0,346,8.0,100898.0,3718.0,1230.0,68.0,1619.0,4345737.0,55,-115
2758,24-03-2020,Repatriated travellers,13,0.0,0,0.0,76.0,0.0,0.0,0.0,13.0,NaN,NaN,NaN
1560,17-08-2020,New Brunswick,186,2.0,0,0.0,49893.0,202.0,169.0,0.0,15.0,772094.0,46.4984,-66.1597
405,08-09-2020,British Columbia,6591,213.0,429,2.0,336405.0,2689.0,4978.0,272.0,1400.0,5020302.0,53.7267,-127.648
1118,20-06-2020,Saskatchewan,726,13.0,10,0.0,52798.0,520.0,639.0,3.0,74.0,1168423.0,55,-106
302,28-05-2020,British Columbia,2558,164.0,8,2.0,118177.0,1415.0,2153.0,9.0,241.0,5020302.0,53.7267,-127.648
1704,30-06-2020,Newfoundland and Labrador,261,3.0,0,0.0,17690.0,141.0,258.0,0.0,0.0,523790.0,53,-60
2813,18-05-2020,Repatriated travellers,13,0.0,0,0.0,76.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
1788,14-03-2020,Nova Scotia,0,0.0,0,0.0,481.0,299.0,0.0,0.0,0.0,965382.0,45,-63
967,31-07-2020,Alberta,10843,196.0,127,1.0,571839.0,5785.0,9261.0,148.0,1386.0,4345737.0,55,-115
632,12-03-2020,Quebec,13,0.0,6,0.0,740.0,184.0,0.0,0.0,13.0,8433301.0,53,-70
1262,03-05-2020,Manitoba,270,6.0,1,0.0,26253.0,517.0,237.0,1.0,38.0,1360396.0,56.4152,-98.7391
1924,28-07-2020,Nova Scotia,1067,63.0,0,0.0,63702.0,244.0,1004.0,0.0,0.0,965382.0,45,-63
1273,14-05-2020,Manitoba,278,7.0,-1,0.0,31742.0,326.0,252.0,1.0,30.0,1360396.0,56.4152,-98.7391
954,18-07-2020,Alberta,9219,167.0,0,0.0,485822.0,0.0,8193.0,0.0,859.0,4345737.0,55,-115
817,13-09-2020,Quebec,64986,5780.0,279,0.0,1248937.0,14045.0,57268.0,214.0,1938.0,8433301.0,53,-70
76,10-05-2020,Ontario,20238,1634.0,294,35.0,419802.0,17041.0,14772.0,389.0,3832.0,14446515.0,50,-85
1406,16-03-2020,New Brunswick,1,0.0,4,0.0,143.0,61.0,0.0,0.0,6.0,772094.0,46.4984,-66.1597
2494,22-07-2020,Nunavut,0,0.0,0,0.0,1273.0,27.0,0.0,0.0,0.0,38787.0,70.4533,-86.799
2521,18-08-2020,Nunavut,0,0.0,0,0.0,1591.0,11.0,0.0,0.0,0.0,38787.0,70.4533,-86.799
1362,11-08-2020,Manitoba,547,8.0,4,0.0,102391.0,1290.0,360.0,6.0,194.0,1360396.0,56.4152,-98.7391
909,03-06-2020,Alberta,7076,145.0,19,2.0,244780.0,4303.0,6587.0,50.0,344.0,4345737.0,55,-115
1108,10-06-2020,Saskatchewan,658,13.0,2,0.0,47730.0,483.0,624.0,0.0,21.0,1168423.0,55,-106
111,14-06-2020,Ontario,32189,2519.0,197,12.0,970926.0,22516.0,26961.0,423.0,2709.0,14446515.0,50,-85
2604,01-05-2020,Yukon,11,0.0,0,0.0,999.0,15.0,11.0,2.0,0.0,40369.0,64,-135
569,26-07-2020,Canada,113898,8890.0,355,5.0,3801950.0,40023.0,99355.0,240.0,5666.0,NaN,NaN,NaN
736,24-06-2020,Quebec,54937,5441.0,53,17.0,568997.0,4533.0,23710.0,90.0,25786.0,8433301.0,53,-70
88,22-05-2020,Ontario,24628,2021.0,441,28.0,569699.0,10907.0,18767.0,258.0,3840.0,14446515.0,50,-85

In [17]:
canada_df=canada_covid_df.loc[canada_covid_df["prname"]=="Canada"]

In [18]:
canada_df=canada_df[["date", "numconf","numtestedtoday","numtoday","numdeathstoday", "numactive"]]

In [19]:
covid_trends_df=canada_df.merge(trend_df, on='date', how='inner')

In [20]:
covid_trends_df

,date,numconf,numtestedtoday,numtoday,numdeathstoday,numactive,CERB,Mask,Bike,Zoom,Patio
0,31-01-2020,4,0.0,4,0.0,4.0,0.0,17.0,7.0,2.0,1.0
1,08-02-2020,7,0.0,3,0.0,7.0,0.0,10.0,7.0,3.0,1.0
2,16-02-2020,8,0.0,1,0.0,8.0,0.0,8.0,9.0,2.0,2.0
3,21-02-2020,9,0.0,1,0.0,9.0,0.0,6.0,6.0,2.0,1.0
4,24-02-2020,10,0.0,1,0.0,10.0,0.0,7.0,8.0,3.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...
201,12-09-2020,136141,22922.0,515,7.0,6896.0,7.0,19.0,18.0,8.0,6.0
202,13-09-2020,136659,85216.0,518,1.0,7057.0,7.0,20.0,18.0,10.0,5.0
203,14-09-2020,138010,80997.0,1351,8.0,7607.0,10.0,19.0,14.0,19.0,4.0
204,15-09-2020,138803,56695.0,793,9.0,7775.0,11.0,19.0,15.0,20.0,4.0
205,16-09-2020,139747,62497.0,944,5.0,8105.0,10.0,19.0,12.0,21.0,5.0

In [21]:
covid_trends_df.columns.tolist()

['date',
 'numconf',
 'numtestedtoday',
 'numtoday',
 'numdeathstoday',
 'numactive',
 'CERB',
 'Mask',
 'Bike',
 'Zoom',
 'Patio']

In [22]:
canada_covid_df.columns.tolist()

['date',
 'prname',
 'numconf',
 'numdeaths',
 'numtoday',
 'numdeathstoday',
 'numtested',
 'numtestedtoday',
 'numrecover',
 'numrecoveredtoday',
 'numactive',
 'population',
 'latitude',
 'longitude']

In [23]:
# change the xxxx to your postgreSQL password when you run the code

connection_string = "postgres:123@localhost:5432/covid_vision"
engine = create_engine(f'postgresql://{connection_string}')

In [24]:
engine.table_names()

['covid_trends', 'canada_covid']

In [25]:
covid_trends_df.to_sql(name = "covid_trends", con=engine, if_exists = 'append', index = True)

In [26]:
canada_covid_df.to_sql(name = "canada_covid", con=engine, if_exists = 'append', index = True)