In [1]:
import pandas as pd

import matplotlib as plt

In [2]:
path="Resources/googletrends.csv"

data = pd.read_csv(path) 

data.columns=['Date','CERB','Mask','Bike','Zoom', 'Patio']
data=data.drop(data.index[[0,1]])
data=data.reset_index()
data.head()

   index        Date CERB Mask Bike Zoom Patio
0      2  2020-01-01   <1    5    7    1     1
1      3  2020-01-02   <1    4    7    2     1
2      4  2020-01-03   <1    5    7    1     1
3      5  2020-01-04   <1    4    8    2     1
4      6  2020-01-05    0    5    8    2     1

In [3]:
trend_df=data.drop('index', axis=1)
trend_df.head()

         Date CERB Mask Bike Zoom Patio
0  2020-01-01   <1    5    7    1     1
1  2020-01-02   <1    4    7    2     1
2  2020-01-03   <1    5    7    1     1
3  2020-01-04   <1    4    8    2     1
4  2020-01-05    0    5    8    2     1

In [4]:
trend_df['Date']=pd.to_datetime(trend_df['Date'], errors='coerce').copy()
trend_df['CERB'] = trend_df['CERB'].replace(
    {'<1': '0'})

In [5]:
trend_df['CERB']=trend_df['CERB'].astype('str', copy=True).astype('float', copy=True)
trend_df['Mask']=trend_df['Mask'].astype('str', copy=True).astype('float', copy=True)
trend_df['Bike']=trend_df['Bike'].astype('str', copy=True).astype('float', copy=True)
trend_df['Zoom']=trend_df['Zoom'].astype('str', copy=True).astype('float', copy=True)
trend_df['Patio']=trend_df['Patio'].astype('str', copy=True).astype('float', copy=True)

trend_df.dtypes

Date     datetime64[ns]
CERB            float64
Mask            float64
Bike            float64
Zoom            float64
Patio           float64
dtype: object

In [6]:
trend_df.head()

        Date  CERB  Mask  Bike  Zoom  Patio
0 2020-01-01   0.0   5.0   7.0   1.0    1.0
1 2020-01-02   0.0   4.0   7.0   2.0    1.0
2 2020-01-03   0.0   5.0   7.0   1.0    1.0
3 2020-01-04   0.0   4.0   8.0   2.0    1.0
4 2020-01-05   0.0   5.0   8.0   2.0    1.0

In [7]:
n_path="Resources/covid19.csv"

cdata = pd.read_csv(n_path) 
cdata.head()

,pruid,prname,prnameFR,date,numconf,numprob,numdeaths,numtotal,numtested,numrecover,...,percentdeath,numtestedtoday,numrecoveredtoday,percentactive,numactive,rateactive,numtotal_last14,ratetotal_last14,numdeaths_last14,ratedeaths_last14
0,35,Ontario,Ontario,31-01-2020,3,0,0.0,3,NaN,NaN,...,0.0,NaN,NaN,100.0,3.0,0.02,NaN,NaN,NaN,NaN
1,59,British Columbia,Colombie-Britannique,31-01-2020,1,0,0.0,1,NaN,NaN,...,0.0,NaN,NaN,100.0,1.0,0.02,NaN,NaN,NaN,NaN
2,1,Canada,Canada,31-01-2020,4,0,0.0,4,NaN,NaN,...,0.0,NaN,NaN,100.0,4.0,0.01,NaN,NaN,NaN,NaN
3,35,Ontario,Ontario,08-02-2020,3,0,0.0,3,NaN,NaN,...,0.0,NaN,NaN,100.0,3.0,0.02,NaN,NaN,NaN,NaN
4,59,British Columbia,Colombie-Britannique,08-02-2020,4,0,0.0,4,NaN,NaN,...,0.0,NaN,NaN,100.0,4.0,0.08,NaN,NaN,NaN,NaN

In [8]:
candata=cdata[[ 'date','prname','numconf','numdeaths','numdeathstoday','numtested','numtestedtoday','numrecover', 
     'numrecoveredtoday','numactive'
     ]]

In [9]:
candata["numdeaths"] = candata["numdeaths"].fillna(0).copy()
candata["numdeathstoday"] = candata["numdeathstoday"].fillna(0).copy()
candata["numtested"] = candata["numtested"].fillna(0).copy()
candata["numtestedtoday"] = candata["numtestedtoday"].fillna(0).copy()
candata["numrecover"] = candata["numrecover"].fillna(0).copy()
candata["numrecoveredtoday"] = candata["numrecoveredtoday"].fillna(0).copy()
candata["numactive"] = candata["numactive"].fillna(0).copy()

/Users/angelaromansivirichi/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/Users/angelaromansivirichi/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/Users/angelaromansivirichi/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/Users/angelaromansivirichi/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/Users/angelaromansivirichi/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/Users/angelaromansivirichi/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/Users/angelaromansivirichi/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys

In [10]:
candata.head(10)

,date,prname,numconf,numdeaths,numdeathstoday,numtested,numtestedtoday,numrecover,numrecoveredtoday,numactive
0,31-01-2020,Ontario,3,0.0,0.0,0.0,0.0,0.0,0.0,3.0
1,31-01-2020,British Columbia,1,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,31-01-2020,Canada,4,0.0,0.0,0.0,0.0,0.0,0.0,4.0
3,08-02-2020,Ontario,3,0.0,0.0,0.0,0.0,0.0,0.0,3.0
4,08-02-2020,British Columbia,4,0.0,0.0,0.0,0.0,0.0,0.0,4.0
5,08-02-2020,Canada,7,0.0,0.0,0.0,0.0,0.0,0.0,7.0
6,16-02-2020,Ontario,3,0.0,0.0,0.0,0.0,0.0,0.0,3.0
7,16-02-2020,British Columbia,5,0.0,0.0,0.0,0.0,0.0,0.0,5.0
8,16-02-2020,Canada,8,0.0,0.0,0.0,0.0,0.0,0.0,8.0
9,21-02-2020,Ontario,3,0.0,0.0,0.0,0.0,0.0,0.0,3.0

In [11]:
provinces_url = "https://www.latlong.net/category/provinces-40-60.html"
territories_url = "https://www.latlong.net/category/territories-40-61.html"
popullation_url ="https://worldpopulationreview.com/canadian-provinces"

provinces_tables = pd.read_html(provinces_url)
territories_tables = pd.read_html(territories_url)
population_tables = pd.read_html(popullation_url)

prov_lat_long_df = provinces_tables[0]
terr_lat_long_df = territories_tables[0]
population_df = population_tables[0]

In [12]:
#population
population_2019_df=population_df.drop(['2016 Population', '2011 Population'], axis=1)
population_2019_df = population_2019_df.sort_values(by='Name', ascending=True)
population_2019_df.reset_index(drop = True, inplace=True)
population_2019_df

                    Name  2019 Population
0                Alberta          4345737
1       British Columbia          5020302
2               Manitoba          1360396
3          New Brunswick           772094
4           Newfoundland           523790
5    Northwest Territory            44598
6            Nova Scotia           965382
7                Nunavut            38787
8                Ontario         14446515
9   Prince Edward Island           154748
10                Quebec          8433301
11          Saskatchewan          1168423
12                 Yukon            40369

In [13]:
#coordinates
coordinates_df = pd.concat([prov_lat_long_df, terr_lat_long_df])
clean_coordinates_df = coordinates_df.reset_index(drop = True).drop(8)
canada_coordinates_df = clean_coordinates_df.reset_index(drop = True)
canada_coordinates_df.loc['12'] = ['Northwest Territories', '64.8255', '-124.8457']
canada_coordinates_df = canada_coordinates_df.sort_values(by='Place Name', ascending=True)
canada_coordinates_df.reset_index(drop = True, inplace=True)
canada_coordinates_df

                                    Place Name Latitude  Longitude
0                     Alberta Province, Canada       55       -115
1                     British Columbia, Canada  53.7267   -127.648
2                             Manitoba, Canada  56.4152   -98.7391
3                        New Brunswick, Canada  46.4984   -66.1597
4   Newfoundland and Labrador Province, Canada       53        -60
5                        Northwest Territories  64.8255  -124.8457
6                          Nova Scotia, Canada       45        -63
7                              Nunavut, Canada  70.4533    -86.799
8                     Ontario Province, Canada       50        -85
9                 Prince Edward Island, Canada    46.25        -63
10                     Quebec Province, Canada       53        -70
11               Saskatchewan Province, Canada       55       -106
12                     Yukon Territory, Canada       64       -135

In [23]:
#population and coordines combined
territories = pd.concat([population_2019_df, canada_coordinates_df], axis=1, join='inner')
territories_df = territories.drop(['Place Name'], axis=1)
territories_df.rename(columns={'2019 Population': 'population', 'Latitude': 'latitude', 'Longitude': 'longitude'}, inplace=True)
territories_df.rename(columns={'Name': 'prname'}, inplace=True)
territories_df['prname'] = territories_df['prname'].replace(['Newfoundland'],'Newfoundland and Labrador')
territories_df['prname'] = territories_df['prname'].replace(['Northwest Territory'],'Northwest Territories')

In [24]:
canada_covid_df = candata.merge(territories_df, on='prname', how='outer')
canada_covid_df.sample(40)

,date,prname,numconf,numdeaths,numdeathstoday,numtested,numtestedtoday,numrecover,numrecoveredtoday,numactive,population,latitude,longitude
590,16-08-2020,Canada,122087,9026.0,2.0,4778360.0,37214.0,108484.0,267.0,4577.0,NaN,NaN,NaN
510,28-05-2020,Canada,88501,6877.0,112.0,1585235.0,54304.0,46853.0,676.0,34782.0,NaN,NaN,NaN
500,18-05-2020,Canada,78061,5842.0,60.0,1323447.0,22718.0,39238.0,688.0,32992.0,NaN,NaN,NaN
1785,11-03-2020,Nova Scotia,0,0.0,0.0,103.0,103.0,0.0,0.0,0.0,965382.0,45,-63
966,30-07-2020,Alberta,10716,195.0,5.0,566054.0,6122.0,9113.0,130.0,1408.0,4345737.0,55,-115
393,27-08-2020,British Columbia,5372,204.0,1.0,292792.0,3493.0,4253.0,54.0,915.0,5020302.0,53.7267,-127.648
1033,27-03-2020,Saskatchewan,104,0.0,0.0,7360.0,631.0,3.0,0.0,101.0,1168423.0,55,-106
2257,07-06-2020,Northwest Territories,5,0.0,0.0,2097.0,0.0,5.0,0.0,0.0,44598.0,64.8255,-124.8457
1283,24-05-2020,Manitoba,281,7.0,0.0,37903.0,878.0,268.0,0.0,17.0,1360396.0,56.4152,-98.7391
437,16-03-2020,Canada,324,5.0,3.0,37730.0,12753.0,0.0,0.0,336.0,NaN,NaN,NaN
1123,25-06-2020,Saskatchewan,759,13.0,0.0,55418.0,485.0,648.0,5.0,98.0,1168423.0,55,-106
1924,28-07-2020,Nova Scotia,1067,63.0,0.0,63702.0,244.0,1004.0,0.0,0.0,965382.0,45,-63
1254,25-04-2020,Manitoba,256,6.0,0.0,21720.0,0.0,199.0,3.0,62.0,1360396.0,56.4152,-98.7391
236,23-03-2020,British Columbia,472,13.0,3.0,23460.0,1325.0,0.0,0.0,459.0,5020302.0,53.7267,-127.648
2003,06-04-2020,Prince Edward Island,22,0.0,0.0,839.0,0.0,8.0,2.0,14.0,154748.0,46.25,-63
391,25-08-2020,British Columbia,5242,203.0,0.0,286955.0,1611.0,4114.0,46.0,925.0,5020302.0,53.7267,-127.648
1459,08-05-2020,New Brunswick,120,0.0,0.0,16068.0,368.0,118.0,0.0,2.0,772094.0,46.4984,-66.1597
2852,26-06-2020,Repatriated travellers,13,0.0,0.0,76.0,0.0,13.0,0.0,0.0,NaN,NaN,NaN
2325,14-08-2020,Northwest Territories,5,0.0,0.0,3126.0,19.0,5.0,0.0,0.0,44598.0,64.8255,-124.8457
1746,11-08-2020,Newfoundland and Labrador,268,3.0,0.0,27298.0,253.0,263.0,0.0,2.0,523790.0,53,-60
1080,13-05-2020,Saskatchewan,577,6.0,0.0,35189.0,388.0,385.0,11.0,186.0,1168423.0,55,-106
1606,24-03-2020,Newfoundland and Labrador,4,0.0,0.0,1087.0,193.0,0.0,0.0,35.0,523790.0,53,-60
1497,15-06-2020,New Brunswick,160,2.0,0.0,34261.0,307.0,129.0,0.0,29.0,772094.0,46.4984,-66.1597
525,12-06-2020,Canada,97932,8049.0,55.0,2072096.0,43600.0,58523.0,865.0,31371.0,NaN,NaN,NaN
1375,24-08-2020,Manitoba,993,12.0,0.0,124109.0,4549.0,586.0,10.0,395.0,1360396.0,56.4152,-98.7391
2621,18-05-2020,Yukon,11,0.0,0.0,1124.0,0.0,11.0,0.0,0.0,40369.0,64,-135
1368,17-08-2020,Manitoba,731,9.0,0.0,113224.0,5299.0,490.0,7.0,232.0,1360396.0,56.4152,-98.7391
1383,01-09-2020,Manitoba,1232,14.0,0.0,134885.0,983.0,759.0,28.0,459.0,1360396.0,56.4152,-98.7391
2841,15-06-2020,Repatriated travellers,13,0.0,0.0,76.0,0.0,13.0,0.0,0.0,NaN,NaN,NaN
2633,30-05-2020,Yukon,11,0.0,0.0,1176.0,0.0,11.0,0.0,0.0,40369.0,64,-135
542,29-06-2020,Canada,103907,8566.0,44.0,2721685.0,44980.0,67178.0,987.0,28174.0,NaN,NaN,NaN
1243,14-04-2020,Manitoba,229,4.0,0.0,17789.0,670.0,0.0,0.0,242.0,1360396.0,56.4152,-98.7391
1171,12-08-2020,Saskatchewan,1484,20.0,0.0,98890.0,785.0,1314.0,20.0,150.0,1168423.0,55,-106
2643,09-06-2020,Yukon,11,0.0,0.0,1219.0,5.0,11.0,0.0,0.0,40369.0,64,-135
175,17-08-2020,Ontario,40745,2789.0,0.0,2522940.0,24731.0,37036.0,83.0,920.0,14446515.0,50,-85
1701,27-06-2020,Newfoundland and Labrador,261,3.0,0.0,17165.0,127.0,258.0,0.0,0.0,523790.0,53,-60
2215,26-04-2020,Northwest Territories,5,0.0,0.0,1575.0,21.0,5.0,0.0,0.0,44598.0,64.8255,-124.8457
2046,19-05-2020,Prince Edward Island,27,0.0,0.0,4761.0,0.0,27.0,0.0,0.0,154748.0,46.25,-63
23,18-03-2020,Ontario,189,1.0,0.0,13869.0,2702.0,0.0,0.0,188.0,14446515.0,50,-85
2866,10-07-2020,Repatriated travellers,13,0.0,0.0,76.0,0.0,13.0,0.0,0.0,NaN,NaN,NaN