In [26]:
import pandas as pd
import datetime as dt
import matplotlib as plt
from sqlalchemy import create_engine

In [2]:
path="Resources/googletrends.csv"

data = pd.read_csv(path) 

data.columns=['date','CERB','Mask','Bike','Zoom', 'Patio']
data=data.drop(data.index[[0,1]])
data=data.reset_index()
data.head()

   index        date CERB Mask Bike Zoom Patio
0      2  01-01-2020   <1    5    7    1     1
1      3  02-01-2020   <1    4    7    2     1
2      4  03-01-2020   <1    5    7    1     1
3      5  04-01-2020   <1    4    8    2     1
4      6  05-01-2020    0    5    8    2     1

In [3]:
trend_df=data.drop('index', axis=1)
trend_df.head()

         date CERB Mask Bike Zoom Patio
0  01-01-2020   <1    5    7    1     1
1  02-01-2020   <1    4    7    2     1
2  03-01-2020   <1    5    7    1     1
3  04-01-2020   <1    4    8    2     1
4  05-01-2020    0    5    8    2     1

In [4]:


trend_df['CERB'] = trend_df['CERB'].replace(
    {'<1': '0'})

In [5]:
trend_df['CERB']=trend_df['CERB'].astype('str', copy=True).astype('float', copy=True)
trend_df['Mask']=trend_df['Mask'].astype('str', copy=True).astype('float', copy=True)
trend_df['Bike']=trend_df['Bike'].astype('str', copy=True).astype('float', copy=True)
trend_df['Zoom']=trend_df['Zoom'].astype('str', copy=True).astype('float', copy=True)
trend_df['Patio']=trend_df['Patio'].astype('str', copy=True).astype('float', copy=True)

trend_df.dtypes

date      object
CERB     float64
Mask     float64
Bike     float64
Zoom     float64
Patio    float64
dtype: object

In [6]:
trend_df.head()

         date  CERB  Mask  Bike  Zoom  Patio
0  01-01-2020   0.0   5.0   7.0   1.0    1.0
1  02-01-2020   0.0   4.0   7.0   2.0    1.0
2  03-01-2020   0.0   5.0   7.0   1.0    1.0
3  04-01-2020   0.0   4.0   8.0   2.0    1.0
4  05-01-2020   0.0   5.0   8.0   2.0    1.0

In [7]:
n_path="Resources/covid19.csv"

cdata = pd.read_csv(n_path) 
cdata.head()

,pruid,prname,prnameFR,date,numconf,numprob,numdeaths,numtotal,numtested,numrecover,...,percentdeath,numtestedtoday,numrecoveredtoday,percentactive,numactive,rateactive,numtotal_last14,ratetotal_last14,numdeaths_last14,ratedeaths_last14
0,35,Ontario,Ontario,31-01-2020,3,0,0.0,3,NaN,NaN,...,0.0,NaN,NaN,100.0,3.0,0.02,NaN,NaN,NaN,NaN
1,59,British Columbia,Colombie-Britannique,31-01-2020,1,0,0.0,1,NaN,NaN,...,0.0,NaN,NaN,100.0,1.0,0.02,NaN,NaN,NaN,NaN
2,1,Canada,Canada,31-01-2020,4,0,0.0,4,NaN,NaN,...,0.0,NaN,NaN,100.0,4.0,0.01,NaN,NaN,NaN,NaN
3,35,Ontario,Ontario,08-02-2020,3,0,0.0,3,NaN,NaN,...,0.0,NaN,NaN,100.0,3.0,0.02,NaN,NaN,NaN,NaN
4,59,British Columbia,Colombie-Britannique,08-02-2020,4,0,0.0,4,NaN,NaN,...,0.0,NaN,NaN,100.0,4.0,0.08,NaN,NaN,NaN,NaN

In [8]:
cdata['prname']=cdata['prname'].astype('str', copy=True)

In [9]:
candata=cdata[[ 'date','prname','numconf','numdeaths','numtoday','numdeathstoday','numtested','numtestedtoday','numrecover', 
     'numrecoveredtoday','numactive'
     ]]

In [10]:
candata["numtoday"] = candata["numtoday"].fillna(0).copy()
candata["numdeaths"] = candata["numdeaths"].fillna(0).copy()
candata["numdeathstoday"] = candata["numdeathstoday"].fillna(0).copy()
candata["numtested"] = candata["numtested"].fillna(0).copy()
candata["numtestedtoday"] = candata["numtestedtoday"].fillna(0).copy()
candata["numrecover"] = candata["numrecover"].fillna(0).copy()
candata["numrecoveredtoday"] = candata["numrecoveredtoday"].fillna(0).copy()
candata["numactive"] = candata["numactive"].fillna(0).copy()

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [11]:
candata.head(10)

,date,prname,numconf,numdeaths,numtoday,numdeathstoday,numtested,numtestedtoday,numrecover,numrecoveredtoday,numactive
0,31-01-2020,Ontario,3,0.0,3,0.0,0.0,0.0,0.0,0.0,3.0
1,31-01-2020,British Columbia,1,0.0,1,0.0,0.0,0.0,0.0,0.0,1.0
2,31-01-2020,Canada,4,0.0,4,0.0,0.0,0.0,0.0,0.0,4.0
3,08-02-2020,Ontario,3,0.0,0,0.0,0.0,0.0,0.0,0.0,3.0
4,08-02-2020,British Columbia,4,0.0,3,0.0,0.0,0.0,0.0,0.0,4.0
5,08-02-2020,Canada,7,0.0,3,0.0,0.0,0.0,0.0,0.0,7.0
6,16-02-2020,Ontario,3,0.0,0,0.0,0.0,0.0,0.0,0.0,3.0
7,16-02-2020,British Columbia,5,0.0,1,0.0,0.0,0.0,0.0,0.0,5.0
8,16-02-2020,Canada,8,0.0,1,0.0,0.0,0.0,0.0,0.0,8.0
9,21-02-2020,Ontario,3,0.0,0,0.0,0.0,0.0,0.0,0.0,3.0

In [12]:
provinces_url = "https://www.latlong.net/category/provinces-40-60.html"
territories_url = "https://www.latlong.net/category/territories-40-61.html"
popullation_url ="https://worldpopulationreview.com/canadian-provinces"

provinces_tables = pd.read_html(provinces_url)
territories_tables = pd.read_html(territories_url)
population_tables = pd.read_html(popullation_url)

prov_lat_long_df = provinces_tables[0]
terr_lat_long_df = territories_tables[0]
population_df = population_tables[0]

In [13]:
#population
population_2019_df=population_df.drop(['2016 Population', '2011 Population'], axis=1)
population_2019_df = population_2019_df.sort_values(by='Name', ascending=True)
population_2019_df.reset_index(drop = True, inplace=True)
population_2019_df

                    Name  2019 Population
0                Alberta          4345737
1       British Columbia          5020302
2               Manitoba          1360396
3          New Brunswick           772094
4           Newfoundland           523790
5    Northwest Territory            44598
6            Nova Scotia           965382
7                Nunavut            38787
8                Ontario         14446515
9   Prince Edward Island           154748
10                Quebec          8433301
11          Saskatchewan          1168423
12                 Yukon            40369

In [14]:
#coordinates
coordinates_df = pd.concat([prov_lat_long_df, terr_lat_long_df])
clean_coordinates_df = coordinates_df.reset_index(drop = True).drop(8)
canada_coordinates_df = clean_coordinates_df.reset_index(drop = True)
canada_coordinates_df.loc['12'] = ['Northwest Territories', '64.8255', '-124.8457']
canada_coordinates_df = canada_coordinates_df.sort_values(by='Place Name', ascending=True)
canada_coordinates_df.reset_index(drop = True, inplace=True)
canada_coordinates_df

                                    Place Name Latitude  Longitude
0                     Alberta Province, Canada       55       -115
1                     British Columbia, Canada  53.7267   -127.648
2                             Manitoba, Canada  56.4152   -98.7391
3                        New Brunswick, Canada  46.4984   -66.1597
4   Newfoundland and Labrador Province, Canada       53        -60
5                        Northwest Territories  64.8255  -124.8457
6                          Nova Scotia, Canada       45        -63
7                              Nunavut, Canada  70.4533    -86.799
8                     Ontario Province, Canada       50        -85
9                 Prince Edward Island, Canada    46.25        -63
10                     Quebec Province, Canada       53        -70
11               Saskatchewan Province, Canada       55       -106
12                     Yukon Territory, Canada       64       -135

In [15]:
#population and coordines combined
territories = pd.concat([population_2019_df, canada_coordinates_df], axis=1, join='inner')
territories_df = territories.drop(['Place Name'], axis=1)
territories_df.rename(columns={'2019 Population': 'population', 'Latitude': 'latitude', 'Longitude': 'longitude'}, inplace=True)
territories_df.rename(columns={'Name': 'prname'}, inplace=True)
territories_df['prname'] = territories_df['prname'].replace(['Newfoundland'],'Newfoundland and Labrador')
territories_df['prname'] = territories_df['prname'].replace(['Northwest Territory'],'Northwest Territories')

In [16]:
canada_covid_df = candata.merge(territories_df, on='prname', how='outer')
canada_covid_df.sample(40)

,date,prname,numconf,numdeaths,numtoday,numdeathstoday,numtested,numtestedtoday,numrecover,numrecoveredtoday,numactive,population,latitude,longitude
1277,18-05-2020,Manitoba,279,7.0,1,0.0,34498.0,456.0,257.0,0.0,26.0,1360396.0,56.4152,-98.7391
1127,29-06-2020,Saskatchewan,779,13.0,1,0.0,57842.0,550.0,679.0,18.0,87.0,1168423.0,55,-106
2209,20-04-2020,Northwest Territories,5,0.0,0,0.0,1495.0,19.0,5.0,2.0,0.0,44598.0,64.8255,-124.8457
152,25-07-2020,Ontario,38543,2759.0,138,1.0,1952807.0,28926.0,34240.0,140.0,1544.0,14446515.0,50,-85
758,16-07-2020,Quebec,57001,5646.0,142,10.0,709026.0,9129.0,26253.0,156.0,25102.0,8433301.0,53,-70
2719,24-08-2020,Yukon,15,0.0,0,0.0,2378.0,43.0,15.0,0.0,0.0,40369.0,64,-135
2242,23-05-2020,Northwest Territories,5,0.0,0,0.0,1906.0,0.0,5.0,0.0,0.0,44598.0,64.8255,-124.8457
1614,01-04-2020,Newfoundland and Labrador,175,1.0,23,0.0,2762.0,262.0,10.0,3.0,164.0,523790.0,53,-60
2926,08-09-2020,Repatriated travellers,13,0.0,0,0.0,76.0,0.0,13.0,0.0,0.0,NaN,NaN,NaN
213,25-02-2020,British Columbia,7,0.0,1,0.0,0.0,0.0,0.0,0.0,7.0,5020302.0,53.7267,-127.648
5,25-02-2020,Ontario,4,0.0,0,0.0,0.0,0.0,0.0,0.0,4.0,14446515.0,50,-85
2027,30-04-2020,Prince Edward Island,27,0.0,0,0.0,2922.0,112.0,24.0,0.0,3.0,154748.0,46.25,-63
1645,02-05-2020,Newfoundland and Labrador,259,3.0,0,0.0,8716.0,171.0,231.0,1.0,25.0,523790.0,53,-60
969,02-08-2020,Alberta,10843,196.0,0,0.0,571839.0,0.0,9261.0,0.0,1386.0,4345737.0,55,-115
1322,02-07-2020,Manitoba,314,7.0,0,0.0,63265.0,1083.0,300.0,0.0,18.0,1360396.0,56.4152,-98.7391
524,11-06-2020,Canada,97519,7994.0,405,34.0,2028496.0,39241.0,57658.0,1019.0,31878.0,NaN,NaN,NaN
1048,11-04-2020,Saskatchewan,289,4.0,4,1.0,17716.0,764.0,0.0,0.0,285.0,1168423.0,55,-106
1282,23-05-2020,Manitoba,281,7.0,0,0.0,37025.0,435.0,268.0,1.0,17.0,1360396.0,56.4152,-98.7391
1400,18-09-2020,Manitoba,1540,16.0,40,0.0,157071.0,684.0,1199.0,8.0,325.0,1360396.0,56.4152,-98.7391
1838,03-05-2020,Nova Scotia,971,37.0,8,6.0,31192.0,418.0,624.0,15.0,310.0,965382.0,45,-63
2680,16-07-2020,Yukon,11,0.0,0,0.0,1376.0,11.0,11.0,0.0,0.0,40369.0,64,-135
631,11-03-2020,Quebec,7,0.0,3,0.0,556.0,556.0,0.0,0.0,7.0,8433301.0,53,-70
229,16-03-2020,British Columbia,73,4.0,0,3.0,9926.0,2893.0,0.0,0.0,69.0,5020302.0,53.7267,-127.648
2775,10-04-2020,Repatriated travellers,13,0.0,0,0.0,76.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
2347,05-09-2020,Northwest Territories,5,0.0,0,0.0,3548.0,0.0,5.0,0.0,0.0,44598.0,64.8255,-124.8457
2235,16-05-2020,Northwest Territories,5,0.0,0,0.0,1851.0,10.0,5.0,0.0,0.0,44598.0,64.8255,-124.8457
2631,28-05-2020,Yukon,11,0.0,0,0.0,1163.0,4.0,11.0,0.0,0.0,40369.0,64,-135
560,17-07-2020,Canada,109658,8839.0,405,12.0,3438041.0,50286.0,96689.0,23853.0,4141.0,NaN,NaN,NaN
1181,22-08-2020,Saskatchewan,1597,22.0,2,0.0,110583.0,1395.0,1458.0,19.0,117.0,1168423.0,55,-106
1826,21-04-2020,Nova Scotia,737,10.0,16,1.0,23261.0,592.0,286.0,38.0,441.0,965382.0,45,-63
374,08-08-2020,British Columbia,3934,195.0,0,0.0,239845.0,2598.0,3353.0,0.0,386.0,5020302.0,53.7267,-127.648
1412,22-03-2020,New Brunswick,9,0.0,0,0.0,924.0,59.0,0.0,0.0,17.0,772094.0,46.4984,-66.1597
1820,15-04-2020,Nova Scotia,549,3.0,32,0.0,18245.0,768.0,0.0,0.0,546.0,965382.0,45,-63
736,24-06-2020,Quebec,54937,5441.0,53,17.0,568997.0,4533.0,23710.0,90.0,25786.0,8433301.0,53,-70
360,25-07-2020,British Columbia,3419,191.0,0,0.0,211792.0,2320.0,2934.0,0.0,294.0,5020302.0,53.7267,-127.648
2341,30-08-2020,Northwest Territories,5,0.0,0,0.0,3427.0,0.0,5.0,0.0,0.0,44598.0,64.8255,-124.8457
2282,02-07-2020,Northwest Territories,5,0.0,0,0.0,2396.0,27.0,5.0,0.0,0.0,44598.0,64.8255,-124.8457
101,04-06-2020,Ontario,29403,2357.0,356,45.0,760610.0,20141.0,23208.0,397.0,3838.0,14446515.0,50,-85
621,16-09-2020,Canada,139747,9193.0,944,5.0,6354657.0,62497.0,122449.0,609.0,8105.0,NaN,NaN,NaN
759,17-07-2020,Quebec,57142,5647.0,141,1.0,718928.0,9902.0,49939.0,23686.0,1556.0,8433301.0,53,-70

In [17]:
canada_df=canada_covid_df.loc[canada_covid_df["prname"]=="Canada"]

In [18]:
canada_df=canada_df[["date", "numconf","numtestedtoday","numtoday","numdeathstoday", "numactive"]]

In [19]:
covid_trends_df=canada_df.merge(trend_df, on='date', how='inner')

In [20]:
covid_trends_df

,date,numconf,numtestedtoday,numtoday,numdeathstoday,numactive,CERB,Mask,Bike,Zoom,Patio
0,31-01-2020,4,0.0,4,0.0,4.0,0.0,17.0,7.0,2.0,1.0
1,08-02-2020,7,0.0,3,0.0,7.0,0.0,10.0,7.0,3.0,1.0
2,16-02-2020,8,0.0,1,0.0,8.0,0.0,8.0,9.0,2.0,2.0
3,21-02-2020,9,0.0,1,0.0,9.0,0.0,6.0,6.0,2.0,1.0
4,24-02-2020,10,0.0,1,0.0,10.0,0.0,7.0,8.0,3.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...
201,12-09-2020,136141,22922.0,515,7.0,6896.0,7.0,19.0,18.0,8.0,6.0
202,13-09-2020,136659,85216.0,518,1.0,7057.0,7.0,20.0,18.0,10.0,5.0
203,14-09-2020,138010,80997.0,1351,8.0,7607.0,10.0,19.0,14.0,19.0,4.0
204,15-09-2020,138803,56695.0,793,9.0,7775.0,11.0,19.0,15.0,20.0,4.0
205,16-09-2020,139747,62497.0,944,5.0,8105.0,10.0,19.0,12.0,21.0,5.0

In [21]:
covid_trends_df.columns.tolist()

['date',
 'numconf',
 'numtestedtoday',
 'numtoday',
 'numdeathstoday',
 'numactive',
 'CERB',
 'Mask',
 'Bike',
 'Zoom',
 'Patio']

In [22]:
canada_covid_df.columns.tolist()

['date',
 'prname',
 'numconf',
 'numdeaths',
 'numtoday',
 'numdeathstoday',
 'numtested',
 'numtestedtoday',
 'numrecover',
 'numrecoveredtoday',
 'numactive',
 'population',
 'latitude',
 'longitude']

In [23]:
# output data frame as csv files
# covid_trends_df.to_csv(r'./Cleaned_CSV/covid_trends.csv')

In [24]:
# canada_covid_df.to_csv(r'./Cleaned_CSV/canada_covid.csv')

In [29]:
# change the xxxx to your postgreSQL password when you run the code

connection_string = "postgres:xxxx@localhost:5432/covid_vision"
engine = create_engine(f'postgresql://{connection_string}')

In [30]:
engine.table_names()

['covid_trends', 'canada_covid']

In [31]:
covid_trends_df.to_sql(name = "covid_trends", con=engine, if_exists = 'append', index = True)

In [32]:
canada_covid_df.to_sql(name = "canada_covid", con=engine, if_exists = 'append', index = True)